server:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

  config:
      import: "classpath:config.properties"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update

  servlet:
    multipart:
      # 파일 저장 확인
      location: C:/Users/kminj/OneDrive/바탕 화면/5mybab
      max-file-size: 10MB
      max-request-size: 10MB

# 본인 파일 경로 확인
upload:
  path: /src/main/resource/picture

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


springdoc:
  packages-to-scan: com.fivemybab.ittabab
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui   # swagger 화면으로 리다이렉션

token:
  secret: ${secret.key}
  expiration_time : ${expiration.time}


